# Generated by Django 4.1.1 on 2023-05-04 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
